#Spring Boot server configuration
spring.datasource.url = jdbc:postgresql://localhost:5433/hotel-reservation-system
spring.datasource.username = postgres
spring.datasource.password = admin
spring.jpa.hibernate.ddl-auto = update

server.address=0.0.0.0
server.port=8083